# Generated by Django 2.1.5 on 2019-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_heading', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
