# Generated by Django 2.1.5 on 2019-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_heading',
            field=models.CharField(max_length=10),
        ),
    ]
