# Generated by Django 2.1.5 on 2019-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=128)),
                ('section_desc', models.CharField(max_length=128)),
            ],
        ),
    ]
